USE master;

IF DB_ID ('LGOIN_DB') IS NOT NULL DROP DATABASE LGOIN_DB;

IF @@ERROR = 3702
   RAISERROR ('Database cannot be dropped because there are still open connections.', 127, 127)
   WITH NOWAIT, LOG;


CREATE DATABASE LGOIN_DB;

GO

USE LGOIN_DB;

GO
CREATE SCHEMA LOGIN AUTHORIZATION dbo;
GO

CREATE TABLE LOGIN.DATA
(
    UserID INT IDENTITY(1,1) NOT NULL,
    PasswordHash BINARY(64) NOT NULL,
    CONSTRAINT [PK_User_UserID] PRIMARY KEY CLUSTERED (UserID ASC)
)
