USE master;

IF DB_ID ('LOGIN') IS NOT NULL DROP DATABASE LOGIN;

IF @@ERROR = 3702
   RAISERROR ('Database cannot be dropped because there are still open connections.', 127, 127)
   WITH NOWAIT, LOG;


CREATE DATABASE LOGIN;

GO

USE LOGIN;

GO
CREATE SCHEMA LOGIN AUTHORIZATION dbo;
GO

CREATE TABLE LOGIN.DATA
(
    id INT IDENTITY(1,1) NOT NULL,
    hash BINARY(64) NOT NULL,
    CONSTRAINT [PK_User_id] PRIMARY KEY CLUSTERED (id ASC)
)
